Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.synced_folder ".", "/srv"

    config.vm.network "private_network", type: "dhcp"

    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end

    config.vm.provision :shell, :inline => "touch .hushlogin"

    # Set preliminaries, git, jdk etc
    config.vm.provision "shell", keep_color: true, path: "provision.sh"

    # Download jessy
    config.vm.provision "shell", run: "always", privileged: false, keep_color: true, path: "build.sh"

    # Open port 5005 for debugging, does not wait for attached debugger
    config.vm.define "server" do |server|
        hostname = "jessy-server"
        server.vm.provision :shell, :inline => "hostnamectl set-hostname #{hostname}"

        if ENV['DEBUG_MACHINE'] == "-s"
            server.vm.network "forwarded_port", guest: 5005, host: 5005
        end

        # Create a fractal configuration based on the current ip
        server.vm.provision "shell", run: "always", privileged: false, keep_color: true do |s|
            s.path = "configure-network.sh"
            s.args = "server"
        end
    end

    # Open port 5005 for debugging, waits for attached debugger before running jessy
    config.vm.define "client" do |client|
        hostname = "jessy-client"
        client.vm.provision :shell, :inline => "hostnamectl set-hostname #{hostname}"

        if ENV['DEBUG_MACHINE'] == "-c"
            client.vm.network "forwarded_port", guest: 5005, host: 5005
        end

        # Copy network settings from server
        client.vm.provision "shell", run: "always", privileged: false, keep_color: true, path: "configure-network.sh"
    end
end
